language: php

services:
  - postgresql

php:
  - '7.1'

addons:
  postgresql: "9.4"

test:
  adapter: postgresql
  database: schema

before_script:
  - psql -c 'create database schema;' -U postgres
  - psql -f './db.sql' -U postgres

script: php ./.tests/lint.php
